[package]
name = "msd"
version = "0.1.0"
edition = "2021"

[dependencies]
itoa = "1.0.1"
ryu = "1.0.9"
serde = "1.0.136"

[build-dependencies]
serde = {version = "1.0.136", default-features = false}

[dev-dependencies]
claim = "0.5.0"
serde_bytes = "0.11.5"
serde_derive = "1.0.136"
