[package]
name = "msd"
version = "0.1.0"
edition = "2021"

[dependencies]
either = "1.6.1"
itoa = "1.0.1"
ryu = "1.0.9"
serde = {version = "1.0.136", default-features = false}

[build-dependencies]
autocfg = "1.0.1"

[dev-dependencies]
claim = "0.5.0"
